export const productList = [
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Sleek Granite Pants",
    price: "587.00",
    qty: "2",
    id: "1",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Tasty Rubber Shirt",
    price: "410.00",
    qty: "5",
    id: "2",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Fantastic Steel Ball",
    price: "109.00",
    qty: "2",
    id: "3",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Ergonomic Granite Pants",
    price: "961.00",
    qty: "7",
    id: "4",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Sleek Fresh Hat",
    price: "465.00",
    qty: "5",
    id: "5",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Handmade Wooden Pizza",
    price: "592.00",
    qty: "8",
    id: "6",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Unbranded Concrete Mouse",
    price: "599.00",
    qty: "6",
    id: "7",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Awesome Frozen Car",
    price: "282.00",
    qty: "1",
    id: "8",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Practical Concrete Table",
    price: "589.00",
    qty: "6",
    id: "9",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Elegant Plastic Pants",
    price: "213.00",
    qty: "4",
    id: "10",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Awesome Rubber Chair",
    price: "955.00",
    qty: "2",
    id: "11",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Electronic Steel Bacon",
    price: "94.00",
    qty: "1",
    id: "12",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Incredible Steel Salad",
    price: "840.00",
    qty: "9",
    id: "13",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Licensed Rubber Keyboard",
    price: "557.00",
    qty: "8",
    id: "14",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Recycled Rubber Fish",
    price: "30.00",
    qty: "4",
    id: "15",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Licensed Concrete Soap",
    price: "417.00",
    qty: "6",
    id: "16",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Licensed Plastic Gloves",
    price: "450.00",
    qty: "7",
    id: "17",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Handcrafted Steel Chips",
    price: "46.00",
    qty: "2",
    id: "18",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Handcrafted Fresh Chicken",
    price: "104.00",
    qty: "8",
    id: "19",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Luxurious Fresh Chair",
    price: "598.00",
    qty: "9",
    id: "20",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Handmade Concrete Fish",
    price: "947.00",
    qty: "8",
    id: "21",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Practical Cotton Bike",
    price: "978.00",
    qty: "5",
    id: "22",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Tasty Fresh Pizza",
    price: "101.00",
    qty: "3",
    id: "23",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Tasty Bronze Gloves",
    price: "595.00",
    qty: "2",
    id: "24",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Luxurious Concrete Table",
    price: "863.00",
    qty: "6",
    id: "25",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Fantastic Plastic Towels",
    price: "868.00",
    qty: "5",
    id: "26",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Generic Concrete Pizza",
    price: "231.00",
    qty: "1",
    id: "27",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Elegant Concrete Chicken",
    price: "957.00",
    qty: "5",
    id: "28",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Incredible Soft Car",
    price: "580.00",
    qty: "7",
    id: "29",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Practical Rubber Tuna",
    price: "686.00",
    qty: "4",
    id: "30",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Fantastic Concrete Shirt",
    price: "630.00",
    qty: "2",
    id: "31",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Gorgeous Plastic Pizza",
    price: "796.00",
    qty: "5",
    id: "32",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Elegant Concrete Computer",
    price: "696.00",
    qty: "8",
    id: "33",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Ergonomic Wooden Salad",
    price: "215.00",
    qty: "9",
    id: "34",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Modern Cotton Salad",
    price: "401.00",
    qty: "4",
    id: "35",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Sleek Rubber Computer",
    price: "861.00",
    qty: "2",
    id: "36",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Intelligent Soft Keyboard",
    price: "756.00",
    qty: "3",
    id: "37",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Handcrafted Bronze Cheese",
    price: "344.00",
    qty: "4",
    id: "38",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Fantastic Rubber Gloves",
    price: "504.00",
    qty: "6",
    id: "39",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Electronic Wooden Keyboard",
    price: "273.00",
    qty: "4",
    id: "40",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Licensed Soft Salad",
    price: "418.00",
    qty: "2",
    id: "41",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Bespoke Fresh Shirt",
    price: "279.00",
    qty: "2",
    id: "42",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Awesome Rubber Sausages",
    price: "132.00",
    qty: "1",
    id: "43",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Handmade Fresh Bike",
    price: "880.00",
    qty: "1",
    id: "44",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Generic Rubber Soap",
    price: "91.00",
    qty: "5",
    id: "45",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Recycled Metal Chips",
    price: "755.00",
    qty: "9",
    id: "46",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Incredible Soft Bacon",
    price: "463.00",
    qty: "2",
    id: "47",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Small Rubber Fish",
    price: "590.00",
    qty: "6",
    id: "48",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Small Cotton Computer",
    price: "463.00",
    qty: "2",
    id: "49",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Sleek Soft Chicken",
    price: "102.00",
    qty: "2",
    id: "50",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Rustic Granite Cheese",
    price: "352.00",
    qty: "9",
    id: "51",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Unbranded Soft Chips",
    price: "369.00",
    qty: "4",
    id: "52",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Electronic Frozen Bacon",
    price: "929.00",
    qty: "9",
    id: "53",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    title: "Tasty Wooden Chicken",
    price: "528.00",
    qty: "2",
    id: "54",
  },
];
